### PR TITLE
display submitter instead of model author

### PR DESCRIPTION
**Pull request by mschrimpf**
image
image

resolve https://github.com/brain-score/brain-score.web/issues/61

### CODE REVIEW

**Comment by pmcgrath249** [comment]
Clean and simple! Excellent :)

**Comment by mschrimpf** [comment]
agree. Here's a first attempt.
image

A question that has come up with this is what to do with the majority of models that we had setup before submissions were even a thing -- do we leave out the user for these or write out the same name (me) for all of them which also looks kinda weird?

**Comment by pmcgrath249** [comment]
Yes, I think it looks great. Also resolves the clutter problem with long email addresses.

Admittedly it looks a little weird, I would write out your name for those anyways. Two reasons:
1. Uniformity, it just looks better
2. You put in the work, give yourself some credit ;)

**Comment by mschrimpf** [comment]
I feel really weird plastering my name all over
image
Maybe this should be "Brain-Score team" or something?

**Comment by pmcgrath249** [comment]
Haha, I would feel weird too. 
Thought about that one as well and I like it. Also, kind of circumvents some problems like:
If you put DiCarlo Lab, it is weird to credit people in the lab in the future.

**Pull request merged**
