### PR TITLE
passing request to index to display users model names

### PR DESCRIPTION
**Pull request by alexriedel1**
Hey,
I'd like to see the model names when I'm logged in so I created this pull request.
I'm not a django developer so I don't know if its safe (and memory efficient?) to pass the request object to the index page. 
But if you think it's ok, I guess it would make the leaderboard look nicer to user and superuser. 

I think the actual way to go would be to create a view for the table..

Also I'm not able to test this so probably there's a mistake somewhere?

### CODE REVIEW

**Comment by mschrimpf** [comment]
Thanks @alexriedel1, could you please post some screenshots of what this looks like?

Alternatively, we could also hash the non-public model names and display the hashes

**Comment by mike-ferguson** [comment]
Hey @alexriedel1! 

We really appreciate your involvement and thanks for bringing this up. We have a solution now thanks to your contribution, and it will be pushed to this branch soon (pending local dev. testing). Feel free to comment anything you like/do not like about this fix after it is pushed (screenshots of the site now will blur out any anon. model details as well :+1:)

Thnx

**Comment by alexriedel1** [comment]
@mike-ferguson 
Thanks! I think this a nice solution

**Review by mschrimpf — APPROVED** [review]

**Comment by mike-ferguson** [comment]
What site now looks like (not logged in) 
image

**Pull request merged**
