### PR TITLE
Adding drop down menus for the model tutorials

### PR DESCRIPTION
**Pull request by jimn2**
Kartik,
Is this what you had in mind for the menus?  (I wasn't able to fully test this locally, because when I click a button, it leaves the local host port).  But I think it should be good.
-Jim

### CODE REVIEW

**Comment by KartikP** [comment]
Jim,

I hope this comment finds you well! This is exactly what I had in mind. There are a few bugs with the formatting of it but this type of navigation bar is perfect.

List of bugs/features/things to change:
1. The green bar that shows up next to the page your on is no longer placed correctly for "Tutorials"
2. If possible, make the popout/dropdown portion of the menu bar a slightly smaller font than the main navigation bar.
3. Make the highlighted color, Brain-Score blue or Brain-Score green.

Thanks for getting this started!

-Kartik

**Comment by jimn2** [comment]
Thanks (yes, all good here).  I just intended this as a rough draft.  Because doing this will also necessitate several other small changes.  But I'll get on it.

**Comment by jimn2** [comment]
Kartik,

I believe this addresses all your comments/concerns (including making the text in the nested dropdown slightly smaller.

**Review by KartikP — COMMENTED** [review]
This looks great @jimn2! Is it possible to move the Dropdown container css that's currently from line 69-132 into the `sidebar.sass` file?

**Comment by jimn2** [comment]
I moved the css to the .sass file.  it was not a straight cut and paste (which I thought I could do) but rather a minor conversion from css to sass.

I also fixed the green bar for the Explore button

**Review by KartikP — APPROVED** [review]
LGTM!

**Pull request merged**
